// SPDX-License-Identifier: Apache-2.0
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Custom API Routes
 *
 * This file is the editable surface for custom backend logic that
 * doesn't fit the auto-generated CRUD model (per-model GET/POST/PATCH/
 * DELETE under `/api/<model>s`). Anything you mount on the exported
 * Hono app shows up at `/api/...` alongside the generated CRUD routes.
 *
 * Examples:
 *   - Aggregations / dashboards: `app.get('/dashboard', ...)`
 *   - Webhooks: `app.post('/webhooks/stripe', ...)`
 *   - Auth flows: `app.post('/auth/login', ...)`
 *
 * For installed integrations (Jira, Slack, Google, Meta Ads, etc.):
 *
 * - Dashboards / list views / "my X" pages → mount a route HERE that
 *   uses `getServerToolsClient()`. Resolve identity per request with
 *   `<TOOLKIT>_GET_CURRENT_USER`, compose the calls you need, return
 *   a clean shape your component owns.
 *
 *   The SDK auto-parses tool result `data` on success (the runtime
 *   JSON.stringifies tool responses; @shogo-ai/sdk/tools >=1.3 parses
 *   them back). Index `data` like a plain object — do NOT write a
 *   `JSON.parse(result.data)` helper. Pass a generic to `execute<T>()`
 *   for typed access.
 *
 *   import { getServerToolsClient } from '@shogo-ai/sdk/tools'
 *
 *   app.get('/jira/my-issues', async (c) => {
 *     const tools = getServerToolsClient()
 *     const me = await tools.execute<{ accountId: string }>('JIRA_GET_CURRENT_USER', {})
 *     if (!me.ok || !me.data?.accountId) {
 *       return c.json({ error: me.error ?? 'not authenticated' }, 401)
 *     }
 *     const issues = await tools.execute<{ issues: unknown[] }>('JIRA_SEARCH_ISSUES', {
 *       jql: `assignee = "${me.data.accountId}"`,
 *     })
 *     if (!issues.ok) return c.json({ error: issues.error ?? 'search failed' }, 502)
 *     return c.json({ issues: issues.data?.issues ?? [] })
 *   })
 *
 *   In the browser, surface the server's `error` field — never throw
 *   `new Error('Failed to load X')`:
 *
 *     const res = await fetch('/api/jira/my-issues')
 *     const body = await res.json().catch(() => ({}))
 *     if (!res.ok) setError(body.error ?? `HTTP ${res.status}`)
 *     else setIssues(body.issues ?? [])
 *
 *   After writing or editing a route, hit it to confirm shape + status:
 *     curl -s -w "\nHTTP %{http_code}\n" http://localhost:$RUNTIME_PORT/api/jira/my-issues
 *   A green build proves the file compiled, not that the endpoint works.
 *
 * - Ad-hoc interactive actions (button clicks, form submits) → use
 *   `useTools()` directly in the component. Don't add a route here for
 *   single-call passthroughs.
 *
 * Hand-rolling a `fetch()` to the provider's REST API will fail
 * because the pod has no provider tokens — auth lives in the runtime.
 * NEVER hardcode the agent operator's identity (accountId, member id,
 * userId) into route code; resolve it per request as shown above.
 *
 * The runtime watches this file. Saving triggers a fast restart of
 * `server.tsx` (no schema regeneration, no `prisma db push`) so changes
 * land in under a second.
 *
 * The Prisma client is available — import it from `./src/lib/db`:
 *
 *   import { prisma } from './src/lib/db'
 *
 *   app.get('/stats', async (c) => {
 *     const userCount = await prisma.user.count()
 *     return c.json({ userCount })
 *   })
 *
 * Do NOT edit `server.tsx` — it is auto-generated by the SDK from
 * `shogo.config.json` and will be overwritten on the next regeneration.
 */

import { Hono } from 'hono'

const app = new Hono()

// Portfolio routes
app.get('/portfolio/projects', async (c) => {
  const { prisma } = await import('./src/lib/db')
  const projects = await prisma.project.findMany({
    where: { status: 'published' },
    orderBy: { sortOrder: 'asc' },
  })
  return c.json({ projects })
})

app.get('/portfolio/projects/:slug', async (c) => {
  const { prisma } = await import('./src/lib/db')
  const project = await prisma.project.findUnique({
    where: { slug: c.req.param('slug') },
  })
  if (!project) return c.json({ error: 'Project not found' }, 404)
  return c.json({ project })
})

// Seed endpoint (dev only)
app.post('/portfolio/seed', async (c) => {
  const { prisma } = await import('./src/lib/db')
  const projects = [
    {
      title: 'BYOD Management System',
      slug: 'byod-management',
      description: 'Microsoft Hybrid Room BYOD Management Service for detecting, tracking, and managing employee-owned devices and peripherals in meeting spaces.',
      longDescription: 'Built a comprehensive Device (BYOD) Management Service as a crucial part of Microsoft Hybrid Room services. This feature allows organizations to manage meeting spaces where employees bring their own devices such as laptops and tablets. The system automatically detects and records when employees plug in peripherals (cameras, microphones, speakers, displays, etc.) into their devices when joining a meeting.\\n\\nKey capabilities delivered:\\n• Automatic peripheral detection and recording when devices connect to meeting rooms\\n• Full IT visibility into room usage through the Pro Management Portal (PMP)\\n• Real-time integration with Azure Event Hub for streaming peripheral connection events\\n• Cosmos DB storage enabling global scalability for multi-tenant enterprise deployments\\n• Association of peripherals with specific BYOD rooms for comprehensive inventory tracking\\n• Seamless Teams Room services integration for hybrid work environments',
      category: 'web',
      videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&h=450&fit=crop',
      demoUrl: 'https://example.com/demo',
      repoUrl: 'https://github.com/example/byod',
      technologies: JSON.stringify(['React', 'TypeScript', 'Node.js', 'Cosmos DB', 'Azure Event Hub', 'Docker', 'Azure']),
      techColors: JSON.stringify(['#61DAFB', '#3178C6', '#339933', '#0078D4', '#0063B1', '#2496ED', '#0078D4']),
      businessImpact: 'Enabled 50K+ organizations to gain complete visibility into BYOD peripherals with 99.8% detection accuracy and real-time inventory tracking across hybrid rooms',
      impactMetrics: JSON.stringify([
        { label: 'Peripherals Tracked', value: '2M+' },
        { label: 'Detection Accuracy', value: '99.8%' },
        { label: 'Organizations Using', value: '50K+' },
        { label: 'Availability', value: '99.99%' },
      ]),
      featured: true,
      status: 'published',
      sortOrder: 1,
    },
    {
      title: 'AI-Powered Analytics Dashboard',
      slug: 'ai-analytics-dashboard',
      description: 'Real-time analytics dashboard with AI-driven insights, predictive modeling, and automated reporting.',
      longDescription: 'Developed an enterprise analytics platform that transforms raw data into actionable insights using machine learning models. The dashboard processes millions of data points in real-time.\n\nKey features:\n• Real-time data visualization with interactive charts and drill-down capabilities\n• ML-powered anomaly detection that alerts teams before issues impact users\n• Automated report generation scheduled via cron jobs\n• Role-based access control with SSO integration',
      category: 'dashboard',
      videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=450&fit=crop',
      demoUrl: 'https://example.com/analytics-demo',
      technologies: JSON.stringify(['React', 'TypeScript', 'Python', 'PostgreSQL', 'Redis', 'Recharts', 'Prisma']),
      techColors: JSON.stringify(['#61DAFB', '#3178C6', '#3776AB', '#4169E1', '#DC382D', '#FF6B6B', '#2D3748']),
      businessImpact: 'Reduced decision-making time by 60% and improved forecast accuracy by 35%',
      impactMetrics: JSON.stringify([
        { label: 'Data Points/Day', value: '10M+' },
        { label: 'Report Speed', value: '3x Faster' },
        { label: 'Cost Savings', value: '$200K/yr' },
        { label: 'Accuracy', value: '94%' },
      ]),
      featured: true,
      status: 'published',
      sortOrder: 2,
    },
    {
      title: 'SaaS Collaboration Tool',
      slug: 'saas-collaboration',
      description: 'A real-time collaboration platform with document editing, team spaces, and integrated video conferencing.',
      longDescription: 'Built a SaaS collaboration tool that enables teams to work together seamlessly. Features include real-time document editing, persistent chat, and video calls.\n\nTechnical highlights:\n• CRDT-based real-time collaboration engine supporting 100+ concurrent editors\n• End-to-end encryption for all documents and communications\n• WebRTC-powered video conferencing with screen sharing\n• Granular permissions system with team workspaces',
      category: 'saas',
      videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&h=450&fit=crop',
      demoUrl: 'https://example.com/collab-demo',
      technologies: JSON.stringify(['React', 'TypeScript', 'Node.js', 'MongoDB', 'WebSocket', 'WebRTC', 'AWS']),
      techColors: JSON.stringify(['#61DAFB', '#3178C6', '#339933', '#47A248', '#FF6B00', '#FF6B00', '#FF9900']),
      businessImpact: 'Enabled teams to reduce meeting time by 40% and increase productivity',
      impactMetrics: JSON.stringify([
        { label: 'Active Teams', value: '2,500+' },
        { label: 'Documents/Day', value: '100K+' },
        { label: 'Meeting Time', value: '-40%' },
        { label: 'NPS Score', value: '72' },
      ]),
      featured: false,
      status: 'published',
      sortOrder: 3,
    },
    {
      title: 'Mobile Fitness Tracker',
      slug: 'fitness-tracker',
      description: 'Cross-platform fitness app with workout tracking, nutrition logging, and social features.',
      longDescription: 'Designed and developed a comprehensive fitness tracking application that helps users achieve their health goals through data-driven insights and social accountability.\n\nFeatures:\n• GPS-based workout tracking with route mapping\n• AI-powered meal recognition from photos\n• Social feed with workout sharing and challenges\n• Integration with Apple Health and Google Fit',
      category: 'mobile',
      videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=800&h=450&fit=crop',
      demoUrl: 'https://example.com/fitness-demo',
      technologies: JSON.stringify(['React', 'TypeScript', 'Node.js', 'MongoDB', 'Firebase', 'GraphQL']),
      techColors: JSON.stringify(['#61DAFB', '#3178C6', '#339933', '#47A248', '#FFCA28', '#E10098']),
      businessImpact: 'Acquired 100K users in first 3 months with 4.8 App Store rating',
      impactMetrics: JSON.stringify([
        { label: 'Downloads', value: '100K+' },
        { label: 'Rating', value: '4.8★' },
        { label: 'Retention', value: '65%' },
        { label: 'DAU', value: '25K' },
      ]),
      featured: false,
      status: 'published',
      sortOrder: 4,
    },
    {
      title: 'REST API Gateway',
      slug: 'api-gateway',
      description: 'High-performance API gateway handling 1M+ requests/minute with rate limiting and caching.',
      longDescription: 'Architected a scalable API gateway that serves as the central entry point for multiple microservices, handling authentication, rate limiting, request transformation, and response caching.\n\nTechnical achievements:\n• Handles 1M+ requests per minute with p99 latency under 50ms\n• Intelligent caching layer reducing database load by 90%\n• Custom rate limiting with token bucket algorithm\n• API versioning and backward compatibility management',
      category: 'api',
      videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=450&fit=crop',
      technologies: JSON.stringify(['Node.js', 'TypeScript', 'Redis', 'Docker', 'Hono', 'Prisma']),
      techColors: JSON.stringify(['#339933', '#3178C6', '#DC382D', '#2496ED', '#FF6B35', '#2D3748']),
      businessImpact: 'Reduced infrastructure costs by 35% while improving response times',
      impactMetrics: JSON.stringify([
        { label: 'Requests/Min', value: '1M+' },
        { label: 'P99 Latency', value: '<50ms' },
        { label: 'Cost Savings', value: '35%' },
        { label: 'Cache Hit', value: '92%' },
      ]),
      featured: false,
      status: 'published',
      sortOrder: 5,
    },
    {
      title: 'Real-Time Chat Application',
      slug: 'realtime-chat',
      description: 'End-to-end encrypted messaging platform with file sharing, video calls, and team channels.',
      longDescription: 'Developed a secure messaging platform designed for teams that handle sensitive data. Features end-to-end encryption, compliance logging, and enterprise-grade security.\n\nKey features:\n• Signal Protocol-based E2E encryption for all messages\n• File sharing with automatic virus scanning\n• Video and voice calls with recording capabilities\n• Compliance logging for regulated industries',
      category: 'web',
      videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
      thumbnailUrl: 'https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=800&h=450&fit=crop',
      demoUrl: 'https://example.com/chat-demo',
      technologies: JSON.stringify(['React', 'TypeScript', 'Node.js', 'WebSocket', 'PostgreSQL', 'Redis', 'AWS']),
      techColors: JSON.stringify(['#61DAFB', '#3178C6', '#339933', '#FF6B00', '#4169E1', '#DC382D', '#FF9900']),
      businessImpact: 'Chosen by 50+ enterprises for secure team communication',
      impactMetrics: JSON.stringify([
        { label: 'Messages/Day', value: '5M+' },
        { label: 'Enterprises', value: '50+' },
        { label: 'Encryption', value: 'E2E' },
        { label: 'Uptime', value: '99.99%' },
      ]),
      featured: false,
      status: 'published',
      sortOrder: 6,
    },
  ]

  for (const project of projects) {
    await prisma.project.upsert({
      where: { slug: project.slug },
      update: project,
      create: project,
    })
  }

  return c.json({ ok: true, count: projects.length })
})

export default app
